FROM python:3.10-slim

WORKDIR /code

ENV ENV=prod
ENV FLASK_APP=tno/mapeditor_dispatcher/main.py

# To avoid warning from flask dotenv.
RUN touch .env

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

RUN pip install -e .
