"""initial commit

Revision ID: e037fa7ad61e
Revises: 
Create Date: 2024-03-21 22:12:43.700985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e037fa7ad61e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_rest',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('job_name', sa.String(), nullable=False),
    sa.Column('workflow_type', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('REGISTERED', 'ENQUEUED', 'RUNNING', 'SUCCEEDED', 'CANCELLED', 'TIMEOUT', 'ERROR', name='jobreststatus'), nullable=False),
    sa.Column('progress_fraction', sa.Float(), nullable=False),
    sa.Column('progress_message', sa.String(), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('running_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timeout_after_s', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=False),
    sa.Column('input_params_dict', sa.JSON(), nullable=True),
    sa.Column('input_esdl', sa.String(), nullable=False),
    sa.Column('output_esdl', sa.String(), nullable=True),
    sa.Column('logs', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('job_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_rest')
    # ### end Alembic commands ###
