"""add job_priority

Revision ID: f6f4ed834980
Revises: 8c22ec9e5d18
Create Date: 2025-04-14 17:46:57.168598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6f4ed834980'
down_revision: Union[str, None] = '8c22ec9e5d18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_rest', sa.Column('job_priority', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_rest', 'job_priority')
    # ### end Alembic commands ###
